### ISSUE TITLE
[Feature Request] Release files with PS4 SAVEDATA format

### ISSUE THREAD

**Issue by josesilveiraa** [McCaulay/mast1c0re-ps2-elf-loader#2]
Many users doesn't have a ps4 to generate the save file, so with the USB SAVEDATA format (PS4/SAVEDATA/xxxx) it would be easier to ask on forums around the internet for people to resign the save

**Comment by d0x360** [comment]
Nexus mods has tons of save files although most from PC but some modified from a PS4 save.

there's also the Skyrim & Borderlands1 & 2 save creator that essentially works on everything.

that said why not just include a folder with a save in the repo?

**Comment by McCaulay** [comment]
I do not currently have an automated process for creating a pre-set PS4 save file in the build chain. [@StretchEcho](https://twitter.com/StretchEcho) usually releases his built PS4 save files on Twitter.
